["A.md"]
title = "ğŸ¤·ğŸ» NGBoostæ€»è§ˆ"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost/A.md"
date = "2024.08.28"
comments = true

["B.ipynb"]
title = "B.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost/B.ipynb"

["C.ipynb"]
title = "C.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost/C.ipynb"

["D.ipynb"]
title = "D.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost/D.ipynb"

["E.ipynb"]
title = "E.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost/E.ipynb"
