["A.md"]
title = "ğŸ˜† ç¦»ç¾¤å€¼å¯¹æ¨¡å‹çš„å½±å“"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸ‘º æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ/A.md"
comments = true

["B.md"]
title = "ğŸ˜ CatBoostå‚æ•°"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸ‘º æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ/B.md"
comments = true

["C.ipynb"]
title = "C.ipynb"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸ‘º æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ/C.ipynb"

["D.md"]
title = "ğŸ§¸ è‡ªç„¶æ¢¯åº¦&å¸¸è§„æ¢¯åº¦"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸ‘º æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ/D.md"
comments = true

["E.md"]
title = "ğŸ˜– ç›¸å…³ç³»æ•°ä¸å†³å®šç³»æ•°"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸ‘º æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ/E.md"
comments = true
