["A.md"]
title = "ğŸ“ª é»‘è‹¹æœå®‰è£…é—®é¢˜æ€»ç»“"
emoji = ""
info = ""
cover = ""
path = "./0Software/6macOS/A.md"
date = 2021-06-29
comments = true

["B.md"]
title = "ğŸ“ª é»‘è‹¹æœå®‰è£…è®°å½•"
emoji = ""
info = ""
cover = ""
path = "./0Software/6macOS/B.md"
date = 2021-06-29
comments = true

["C.md"]
title = "ğŸ“ª è”æƒ³Y50æ›´æ¢BCM94352zæ— çº¿ç½‘å¡"
emoji = ""
info = ""
cover = ""
path = "./0Software/6macOS/C.md"
date = 2021-06-29
comments = true
