[1env]
title = "1env"
emoji = ""
info = ""
cover = ""
path = "./3Rust/1env"

["1ï¸âƒ£ ç¯å¢ƒé…ç½®"]
title = "1ï¸âƒ£ ç¯å¢ƒé…ç½®"
emoji = ":simple-rust:"
info = ""
cover = ""
path = "./ğŸ Rust/1ï¸âƒ£ ç¯å¢ƒé…ç½®"

[2coding]
title = "2coding"
emoji = ""
info = ""
cover = ""
path = "./3Rust/2coding"

["2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"]
title = "2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"
emoji = ":simple-rust:"
info = ""
cover = ""
path = "./ğŸ Rust/2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"
