["A.md"]
title = "ğŸ‘ Arduinoæ¨¡æ‹ŸModBusåè®®"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/4embedded/A.md"
comments = true

["B.md"]
title = "ğŸ‰ macOSä¸‹Arduinoç¼–ç¨‹"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/4embedded/B.md"
comments = true
