["A.ipynb"]
title = "A.ipynb"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—/A.ipynb"

["B.md"]
title = "ğŸŸ Numpy"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—/B.md"
comments = true

["C.md"]
title = "ğŸ¥£ Scipy"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—/C.md"
comments = true
