["A.md"]
title = "ğŸ¤ Pycharmé…ç½®"
emoji = ""
info = ""
cover = ""
path = "./1Python/0env/A.md"
comments = true

["B.md"]
title = "ğŸŒ©ï¸ åˆ›å»ºrequirements"
emoji = ""
info = ""
cover = ""
path = "./1Python/0env/B.md"
comments = true

["C.md"]
title = "Jupyter Labæ’ä»¶"
emoji = ""
info = ""
cover = ""
path = "./1Python/0env/C.md"
date = "2025.04.12"

["G.md"]
title = "ğŸ¿ é…ç½®Jupyterè¿œç¨‹è®¿é—®"
emoji = ""
info = ""
cover = ""
path = "./1Python/0env/G.md"
comments = true
date = "2023.11.28"
