[0coding]
title = "0coding"
emoji = ""
info = ""
cover = ""
path = "./1Python/0coding"

[0env]
title = "0env"
emoji = ""
info = ""
cover = ""
path = "./1Python/0env"

[0packages]
title = "0packages"
emoji = ""
info = ""
cover = ""
path = "./1Python/0packages"

["0ï¸âƒ£ PyCharmé…ç½®"]
title = "0ï¸âƒ£ PyCharmé…ç½®"
info = ""
emoji = ":simple-pycharm:"
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ PyCharmé…ç½®"

["0ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"]
title = "0ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"
info = ""
emoji = ":octicons-terminal-16:"
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"

["0ï¸âƒ£ æ‰©å±•åº“"]
title = "0ï¸âƒ£ æ‰©å±•åº“"
info = ""
emoji = ":simple-pypi:"
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ æ‰©å±•åº“"

[1rye]
title = "1rye"
emoji = ""
info = ""
cover = ""
path = "./1Python/1rye"

["1ï¸âƒ£ Ryeç›¸å…³"]
title = "1ï¸âƒ£ Ryeç›¸å…³"
info = ""
emoji = ":simple-rye:"
cover = ""
path = "./ğŸ¦ Python/1ï¸âƒ£ Ryeç›¸å…³"

[2conda]
title = "2conda"
emoji = ""
info = ""
cover = ""
path = "./1Python/2conda"

["2ï¸âƒ£ Condaç›¸å…³"]
title = "2ï¸âƒ£ Condaç›¸å…³"
info = ""
emoji = ":simple-anaconda:"
cover = ""
path = "./ğŸ¦ Python/2ï¸âƒ£ Condaç›¸å…³"

[3pip]
title = "3pip"
emoji = ""
info = ""
cover = ""
path = "./1Python/3pip"

["3ï¸âƒ£ pipç›¸å…³"]
title = "3ï¸âƒ£ pipç›¸å…³"
info = ""
emoji = ":simple-pypi:"
cover = ""
path = "./ğŸ¦ Python/3ï¸âƒ£ pipç›¸å…³"

[4gui]
title = "4gui"
emoji = ""
info = ""
cover = ""
path = "./1Python/4gui"

[5visdom]
title = "5visdom"
emoji = ""
info = ""
cover = ""
path = "./1Python/5visdom"

["5ï¸âƒ£ Pythonå¯è§†åŒ–"]
title = "5ï¸âƒ£ Pythonå¯è§†åŒ–"
info = ""
emoji = ":simple-plotly:"
cover = ""
path = "./ğŸ¦ Python/5ï¸âƒ£ Pythonå¯è§†åŒ–"

["6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—"]
title = "6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—"
info = ""
emoji = ":simple-numpy:"
cover = ""
path = "./ğŸ¦ Python/6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—"

["7ï¸âƒ£ Pythonç½‘ç»œç¼–ç¨‹"]
title = "7ï¸âƒ£ Pythonç½‘ç»œç¼–ç¨‹"
info = ""
emoji = ":simple-flask:"
cover = ""
path = "./ğŸ¦ Python/7ï¸âƒ£ Pythonç½‘ç»œç¼–ç¨‹"

["8ï¸âƒ£ Python GUIç¼–ç¨‹"]
title = "8ï¸âƒ£ Python GUIç¼–ç¨‹"
info = ""
emoji = ":simple-flutter:"
cover = ""
path = "./ğŸ¦ Python/8ï¸âƒ£ Python GUIç¼–ç¨‹"

["9ï¸âƒ£ Pythonç¡¬ä»¶ç¼–ç¨‹"]
title = "9ï¸âƒ£ Pythonç¡¬ä»¶ç¼–ç¨‹"
info = ""
emoji = ":simple-arduino:"
cover = ""
path = "./ğŸ¦ Python/9ï¸âƒ£ Pythonç¡¬ä»¶ç¼–ç¨‹"

["ğŸ”Ÿ å…¶ä»–"]
title = "ğŸ”Ÿ å…¶ä»–"
info = ""
emoji = ":simple-python:"
cover = ""
path = "./ğŸ¦ Python/ğŸ”Ÿ å…¶ä»–"
