["A0.ipynb"]
title = "A0.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/A0.ipynb"

["Adatasets.md"]
title = "datasets"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/Adatasets.md"
date = "2024.09.05"
comments = true

["Afit.md"]
title = "ğŸ” fit"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/Afit.md"
comments = true

["Bpredict.md"]
title = "ğŸ¦¢ predict"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/Bpredict.md"
date = "2024.09.05"
comments = true

["FeaturesData.md"]
title = "FeaturesData"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/FeaturesData.md"
comments = true

["IpythonWidget.md"]
title = "CatBoostIpythonWidget"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/IpythonWidget.md"
comments = true

["Pool.md"]
title = "Pool"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/Pool.md"
comments = true

["Shrink.md"]
title = "Shrink"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/Shrink.md"
comments = true

["calc_feature_statistics.md"]
title = "ğŸ calc_feature_statistics"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/calc_feature_statistics.md"
date = "2024.09.05"
comments = true

["calc_leaf_indexes.md"]
title = "â›„ calc_leaf_indexes"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/calc_leaf_indexes.md"
date = "2024.09.05"
comments = true

["compare.md"]
title = "â›„ compare"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/compare.md"
date = "2024.09.05"
comments = true

["copy.md"]
title = "â›„ copy"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/copy.md"
date = "2024.09.05"
comments = true

["cv.md"]
title = "cv"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/cv.md"
comments = true

["eval_metrics.md"]
title = "â›„ eval_metrics"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/eval_metrics.md"
date = "2024.09.05"
comments = true

["get_all_params.md"]
title = "â›„ get_all_params"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_all_params.md"
date = "2024.09.05"
comments = true

["get_best_iteration.md"]
title = "â›„ get_best_iteration"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_best_iteration.md"
date = "2024.09.05"
comments = true

["get_best_score.md"]
title = "â›„ get_best_score"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_best_score.md"
date = "2024.09.05"
comments = true

["get_borders.md"]
title = "â›„ get_borders"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_borders.md"
date = "2024.09.05"
comments = true

["get_evals_result.md"]
title = "â›„ get_evals_result"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_evals_result.md"
date = "2024.09.05"
comments = true

["get_feature_importance.md"]
title = "â›„ get_feature_importance"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_feature_importance.md"
date = "2024.09.05"
comments = true

["get_object_importance.md"]
title = "â›„ get_object_importance"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_object_importance.md"
date = "2024.09.05"
comments = true

["get_param.md"]
title = "â›„ get_param"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_param.md"
date = "2024.09.05"
comments = true

["get_params.md"]
title = "â›„ get_params"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_params.md"
date = "2024.09.05"
comments = true

["get_scale_and_bias.md"]
title = "â›„ get_scale_and_bias"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_scale_and_bias.md"
date = "2024.09.05"
comments = true

["get_test_eval.md"]
title = "â›„ get_test_eval"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/get_test_eval.md"
date = "2024.09.05"
comments = true

["grid_search.md"]
title = "â›„ grid_search"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/grid_search.md"
date = "2024.09.05"
comments = true

["is_fitted.md"]
title = "â›„ is_fitted"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/is_fitted.md"
date = "2024.09.05"
comments = true

["load_model.md"]
title = "â›„ load_model"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/load_model.md"
date = "2024.09.05"
comments = true

["plot_predictions.md"]
title = "â›„ plot_predictions"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/plot_predictions.md"
date = "2024.09.05"
comments = true

["plot_tree.md"]
title = "â›„ plot_tree"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/plot_tree.md"
date = "2024.09.05"
comments = true

["randomized_search.md"]
title = "â›„ randomized_search"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/randomized_search.md"
date = "2024.09.05"
comments = true

["save_borders.md"]
title = "â›„ save_borders"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/save_borders.md"
date = "2024.09.05"
comments = true

["save_model.md"]
title = "â›„ save_model"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/save_model.md"
date = "2024.09.05"
comments = true

["select_features.md"]
title = "â›„ select_features"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/select_features.md"
date = "2024.09.05"
comments = true

["set_feature_names.md"]
title = "â›„ set_feature_names"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/set_feature_names.md"
date = "2024.09.05"
comments = true

["set_params.md"]
title = "â›„ set_params"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/set_params.md"
date = "2024.09.05"
comments = true

["set_scale_and_bias.md"]
title = "â›„ set_scale_and_bias"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/set_scale_and_bias.md"
date = "2024.09.05"
comments = true

["staged_predict.md"]
title = "staged_predict"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/staged_predict.md"
comments = true

["virtual_ensembles_predict.md"]
title = "virtual_ensembles_predict"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost/virtual_ensembles_predict.md"
comments = true
