["1ï¸âƒ£ ç¯å¢ƒé…ç½®"]
title = "1ï¸âƒ£ ç¯å¢ƒé…ç½®"
emoji = ":simple-clion:"
info = ""
cover = ""
path = "./ğŸ C&C++/1ï¸âƒ£ ç¯å¢ƒé…ç½®"

["2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"]
title = "2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"
emoji = ":simple-c:"
info = ""
cover = ""
path = "./ğŸ C&C++/2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"

["3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"]
title = "3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"
emoji = ":simple-doxygen:"
info = ""
cover = ""
path = "./ğŸ C&C++/3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"

["4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"]
title = "4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"
emoji = ":simple-arduino:"
info = ""
cover = ""
path = "./ğŸ C&C++/4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"
