[0software]
title = "0software"
emoji = ""
info = ""
cover = ""
path = "./0Software/0software"

["0ï¸âƒ£ è½¯ä»¶æ¨è"]
title = "0ï¸âƒ£ è½¯ä»¶æ¨è"
emoji = ":simple-opensourceinitiative:"
info = "æ—¥å¸¸å·¥ä½œç”Ÿæ´»ç”¨åˆ°çš„ä¸€äº›è½¯ä»¶"
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/0ï¸âƒ£ è½¯ä»¶æ¨è"

[1Linux]
title = "1Linux"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux"

["1ï¸âƒ£ Linux(Ubuntu)"]
title = "1ï¸âƒ£ Linux(Ubuntu)"
info = "Linuxæ˜¯ä¸€ç§å¼€æºçš„ç±»UNIXæ“ä½œç³»ç»Ÿï¼Œä»¥å…¶ç¨³å®šæ€§ã€å®‰å…¨æ€§å’Œçµæ´»æ€§é—»åï¼Œå¹¿æ³›åº”ç”¨äºæœåŠ¡å™¨ã€æ¡Œé¢ã€ç§»åŠ¨è®¾å¤‡å’ŒåµŒå…¥å¼ç³»ç»Ÿã€‚"
emoji = ":simple-ubuntu:"
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/1ï¸âƒ£ Linux(Ubuntu)"

[2WSL]
title = "2WSL"
emoji = ""
info = ""
cover = ""
path = "./0Software/2WSL"

["2ï¸âƒ£ WSL"]
title = "2ï¸âƒ£ WSL"
info = "WSLï¼ˆWindows Subsystem for Linuxï¼‰æ˜¯å¾®è½¯ä»Win10å¼•å…¥çš„åŠŸèƒ½ï¼Œå…è®¸åœ¨Windowsä¸Šè¿è¡ŒLinuxç¯å¢ƒåŠå…¶å‘½ä»¤è¡Œå·¥å…·å’Œåº”ç”¨ç¨‹åºã€‚"
emoji = ":simple-linux:"
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/2ï¸âƒ£ WSL"

[3Win10]
title = "3Win10"
emoji = ""
info = ""
cover = ""
path = "./0Software/3Win10"

["3ï¸âƒ£ Windows10"]
title = "3ï¸âƒ£ Windows10"
cover = ""
emoji = ":fontawesome-brands-windows:"
info = "Windows 10æ˜¯å¾®è½¯äº2015å¹´æ¨å‡ºçš„æ“ä½œç³»ç»Ÿï¼Œæä¾›äº†å…¨æ–°çš„å¼€å§‹èœå•ã€Cortanaè¯­éŸ³åŠ©æ‰‹ã€Edgeæµè§ˆå™¨ç­‰åŠŸèƒ½ï¼Œæ”¯æŒå¤šè®¾å¤‡æ— ç¼æ“ä½œã€‚"
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/3ï¸âƒ£ Windows10"

[4Win11]
title = "4Win11"
emoji = ""
info = ""
cover = ""
path = "./0Software/4Win11"

["4ï¸âƒ£ Windows11"]
title = "4ï¸âƒ£ Windows11"
info = "Windows 11æ˜¯å¾®è½¯äº2021å¹´æ¨å‡ºçš„æ“ä½œç³»ç»Ÿï¼Œæä¾›äº†æ–°ç‰ˆå¼€å§‹èœå•ï¼Œæ”¯æŒä¸æ—¶ä»£ç›¸ç¬¦çš„æ··åˆå·¥ä½œç¯å¢ƒï¼Œå¹¶ä¾§é‡äºæé«˜ç”¨æˆ·çš„å·¥ä½œæ•ˆç‡ã€‚"
emoji = ":fontawesome-brands-windows:"
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/4ï¸âƒ£ Windows11"

[5Git]
title = "5Git"
emoji = ""
info = ""
cover = ""
path = "./0Software/5Git"

["5ï¸âƒ£ Git"]
title = "5ï¸âƒ£ Git"
info = "Gitæ˜¯ä¸€ä¸ªå¼€æºçš„åˆ†å¸ƒå¼ç‰ˆæœ¬æ§åˆ¶ç³»ç»Ÿï¼Œç”¨äºå¤„ç†é¡¹ç›®ç‰ˆæœ¬ç®¡ç†ã€‚ç”±Linus Torvaldsåˆ›å»ºï¼Œç”¨äºè½¯ä»¶å¼€å‘ä¸­ä»¥åè°ƒä»£ç å˜æ›´å’Œå¤šäººåä½œã€‚"
emoji = ":simple-git:"
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/5ï¸âƒ£ Git"

[6macOS]
title = "6macOS"
emoji = ""
info = ""
cover = ""
path = "./0Software/6macOS"

["6ï¸âƒ£ macOS"]
title = "6ï¸âƒ£ macOS"
cover = ""
emoji = ":material-apple:"
info = "macOSæ˜¯è‹¹æœå…¬å¸å¼€å‘çš„æ¡Œé¢æ“ä½œç³»ç»Ÿï¼Œä¸“ä¸ºMacç”µè„‘è®¾è®¡ã€‚å®ƒä»¥Unixä¸ºåŸºç¡€ï¼Œæä¾›ç›´è§‚çš„å›¾å½¢ç”¨æˆ·ç•Œé¢å’Œå¼ºå¤§çš„å¤šä»»åŠ¡èƒ½åŠ›ã€‚"
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/6ï¸âƒ£ macOS"

[7LOL]
title = "7LOL"
emoji = ""
info = ""
cover = ""
path = "./0Software/7LOL"

["7ï¸âƒ£ è‹±é›„è”ç›Ÿ"]
title = "7ï¸âƒ£ è‹±é›„è”ç›Ÿ"
cover = ""
emoji = ":simple-leagueoflegends:"
info = "è‹±é›„è”ç›Ÿï¼ˆLeague of Legendsï¼‰æ˜¯Riot Gameså¼€å‘çš„è‹±é›„å¯¹æˆ˜ç½‘æ¸¸ï¼Œæ¸¸æˆä»¥ä¸°å¯Œçš„è‹±é›„è§’è‰²ã€å¤šæ ·çš„æ¸¸æˆæ¨¡å¼å’Œå›¢é˜Ÿç«æŠ€ä¸ºç‰¹è‰²ã€‚"
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/7ï¸âƒ£ è‹±é›„è”ç›Ÿ"
