["A.ipynb"]
title = "A.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ /A.ipynb"

["B.ipynb"]
title = "B.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ /B.ipynb"

["C.ipynb"]
title = "C.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ /C.ipynb"

["D.ipynb"]
title = "D.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ /D.ipynb"

["E.ipynb"]
title = "E.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ /E.ipynb"
