["A.md"]
title = "ğŸ¤ Pycharmé…ç½®"
emoji = ""
info = ""
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ PyCharmé…ç½®/A.md"
comments = true

["B.md"]
title = "ğŸŒ©ï¸ åˆ›å»ºrequirements"
emoji = ""
info = ""
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ PyCharmé…ç½®/B.md"
comments = true

["C.md"]
title = "Jupyter Labæ’ä»¶"
emoji = ""
info = ""
cover = ""
path = "./ğŸ¦ Python/0ï¸âƒ£ PyCharmé…ç½®/C.md"
date = "2025.04.12"
