[0compile]
title = "0compile"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/0compile"

["0ï¸âƒ£ ç¼–è¯‘åŸºç¡€çŸ¥è¯†"]
title = "0ï¸âƒ£ ç¼–è¯‘åŸºç¡€çŸ¥è¯†"
emoji = ""
info = ""
cover = ""
path = "./ğŸ C&C++/0ï¸âƒ£ ç¼–è¯‘åŸºç¡€çŸ¥è¯†"

[1env]
title = "1env"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/1env"

["1ï¸âƒ£ ç¯å¢ƒé…ç½®"]
title = "1ï¸âƒ£ ç¯å¢ƒé…ç½®"
emoji = ":simple-clion:"
info = ""
cover = ""
path = "./ğŸ C&C++/1ï¸âƒ£ ç¯å¢ƒé…ç½®"

[2coding]
title = "2coding"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/2coding"

["2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"]
title = "2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"
emoji = ":simple-c:"
info = ""
cover = ""
path = "./ğŸ C&C++/2ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"

[3api_docs]
title = "3api_docs"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/3api_docs"

["3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"]
title = "3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"
emoji = ":simple-doxygen:"
info = ""
cover = ""
path = "./ğŸ C&C++/3ï¸âƒ£ Cå·¥ç¨‹APIæ–‡æ¡£"

[4embedded]
title = "4embedded"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/4embedded"

["4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"]
title = "4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"
emoji = ":simple-arduino:"
info = ""
cover = ""
path = "./ğŸ C&C++/4ï¸âƒ£ åµŒå…¥å¼ç¼–ç¨‹"

[5experience]
title = "5experience"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/5experience"

["5ï¸âƒ£ ç»éªŒæ€»ç»“"]
title = "5ï¸âƒ£ ç»éªŒæ€»ç»“"
emoji = ""
info = ""
cover = ""
path = "./ğŸ C&C++/5ï¸âƒ£ ç»éªŒæ€»ç»“"

[6thoughts]
title = "6thoughts"
emoji = ""
info = ""
cover = ""
path = "./2C&C++/6thoughts"
