["Argparse.md"]
title = "ğŸ˜€ Argparse"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/Argparse.md"
comments = true

["Loguru.md"]
title = "ğŸ¤£ Loguru"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/Loguru.md"
comments = true

["Ruff.md"]
title = "ğŸ¤« Ruff"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/Ruff.md"
comments = true

["SciencePlots.md"]
title = "ğŸ¥° SciencePlots"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/SciencePlots.md"
comments = true

["TensorboardX.md"]
title = "ğŸ¤© TensorbordX"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/TensorboardX.md"
comments = true

["tqdm.ipynb"]
title = "tqdm.ipynb"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/tqdm.ipynb"

["uv.md"]
title = "ğŸ¤  uv"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ æ‰©å±•åº“/uv.md"
date = "2024.03.02"
comments = true
