["A.md"]
title = "ğŸ¥ Ryeä½¿ç”¨æŒ‡å—"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/1ï¸âƒ£ Ryeç›¸å…³/A.md"
comments = true

["B.md"]
title = "ğŸ§© Ryeè¸©å‘è®°å½•"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/1ï¸âƒ£ Ryeç›¸å…³/B.md"
comments = true

["C.md"]
title = "ğŸ”« Ryeå®‰è£…Jupyter"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/1ï¸âƒ£ Ryeç›¸å…³/C.md"
comments = true
