["A.md"]
title = "ğŸ¤ Pycharmé…ç½®"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ PyCharmé…ç½®/A.md"
comments = true

["B.md"]
title = "ğŸŒ©ï¸ åˆ›å»ºrequirements"
emoji = ""
info = ""
cover = ""
path = "../docs/ğŸˆ Python/0ï¸âƒ£ PyCharmé…ç½®/B.md"
comments = true
