["1ï¸âƒ£ ç¯å¢ƒé…ç½®"]
title = "1ï¸âƒ£ ç¯å¢ƒé…ç½®"
info = ""
emoji = ":simple-anaconda:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/1ï¸âƒ£ ç¯å¢ƒé…ç½®"

["2ï¸âƒ£ MkDocs"]
title = "2ï¸âƒ£ MkDocs"
info = ""
emoji = ":simple-materialformkdocs:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/2ï¸âƒ£ MkDocs"

["3ï¸âƒ£ MinIO"]
title = "3ï¸âƒ£ MinIO"
info = ""
emoji = ":simple-minio:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/3ï¸âƒ£ MinIO"

["4ï¸âƒ£ Markdown"]
title = "4ï¸âƒ£ Markdown"
info = ""
emoji = ":simple-markdown:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/4ï¸âƒ£ Markdown"

["5ï¸âƒ£ Apache"]
title = "5ï¸âƒ£ Apache"
info = ""
emoji = ":simple-apache:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/5ï¸âƒ£ Apache"

["6ï¸âƒ£ Hexo"]
title = "6ï¸âƒ£ Hexo"
info = ""
emoji = ":simple-hexo:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/6ï¸âƒ£ Hexo"

["7ï¸âƒ£ å­—ä½“"]
title = "7ï¸âƒ£ å­—ä½“"
info = ""
emoji = ":fontawesome-solid-font:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/7ï¸âƒ£ å­—ä½“"

["8ï¸âƒ£ Notion"]
title = "8ï¸âƒ£ Notion"
info = ""
emoji = ":simple-notion:"
cover = ""
path = "../docs/ğŸˆ å‰ç«¯/8ï¸âƒ£ Notion"
