["A.md"]
title = "ğŸ ç½®ä¿¡å­¦ä¹ "
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ /A.md"
date = "2024.08.20"
comments = true

["B.md"]
title = "ğŸ é—®é¢˜"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ /B.md"
date = "2024.08.20"
comments = true

["cl1.ipynb"]
title = "cl1.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ /cl1.ipynb"

["cl2.ipynb"]
title = "cl2.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ /cl2.ipynb"

["cl3.ipynb"]
title = "cl3.ipynb"
emoji = ""
info = ""
cover = ""
path = "./ğŸ‘º æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ /cl3.ipynb"
