["1ï¸âƒ£ å¼€æºæ•°æ®é›†"]
title = "1ï¸âƒ£ å¼€æºæ•°æ®é›†"
info = "ä¸€äº›å¸¸è§æ•°æ®é›†çš„ç®€å•ä½¿ç”¨"
emoji = ":simple-kaggle:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /1ï¸âƒ£ å¼€æºæ•°æ®é›†"

["3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ"]
title = "3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ"
info = "ä¸€äº›æœºå™¨å­¦ä¹ ç›¸å…³æ¦‚å¿µã€ç†è§£"
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /3ï¸âƒ£ MLç›¸å…³æ¦‚å¿µ"

["4ï¸âƒ£ é›†æˆå­¦ä¹ "]
title = "4ï¸âƒ£ é›†æˆå­¦ä¹ "
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /4ï¸âƒ£ é›†æˆå­¦ä¹ "

["5ï¸âƒ£ è¶…å‚æ•°ä¼˜åŒ–"]
title = "5ï¸âƒ£ è¶…å‚æ•°ä¼˜åŒ–"
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /5ï¸âƒ£ è¶…å‚æ•°ä¼˜åŒ–"

["6ï¸âƒ£ æ¨¡å‹å¯è§£é‡Šæ€§"]
title = "6ï¸âƒ£ æ¨¡å‹å¯è§£é‡Šæ€§"
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /6ï¸âƒ£ æ¨¡å‹å¯è§£é‡Šæ€§"

["7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ "]
title = "7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ "
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /7ï¸âƒ£ ç½®ä¿¡å­¦ä¹ "

["8ï¸âƒ£ NGBoost"]
title = "8ï¸âƒ£ NGBoost"
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /8ï¸âƒ£ NGBoost"

["9ï¸âƒ£ CatBoost"]
title = "9ï¸âƒ£ CatBoost"
info = ""
emoji = ":simple-scikitlearn:"
cover = ""
path = "../docs/ğŸ æœºå™¨å­¦ä¹ /9ï¸âƒ£ CatBoost"
