["A.md"]
title = "ğŸ“ ç³»ç»Ÿå®‰è£…è®°å½•"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/A.md"
date = "2023.10.13"
comments = true

["AA.md"]
title = "ğŸŸ åŸºç¡€ä½¿ç”¨"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/AA.md"
comments = true

["B.md"]
title = "ğŸ… å®‰è£…è½¯ä»¶"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/B.md"
comments = true

["C.md"]
title = "ğŸ¦´ ä¿®æ”¹é•œåƒæº"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/C.md"
comments = true

["D.md"]
title = "ğŸ å®‰è£…å­—ä½“"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/D.md"
date = "2023.10.13"
comments = true

["F.md"]
title = "ğŸ¬ é…ç½®Samba"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/F.md"
comments = true

["G.md"]
title = "ğŸ¿ é…ç½®Jupyterè¿œç¨‹è®¿é—®"
emoji = ""
info = ""
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/1ï¸âƒ£ Linux(Ubuntu)/G.md"
comments = true
date = "2023.11.28"

["H.md"]
title = "ğŸˆ é…ç½®SSH"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/H.md"
comments = true
date = "2023.11.28"

["I.md"]
title = "ğŸ’ å‹ç¼©å‘½ä»¤æ±‡æ€»"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/I.md"
comments = true
date = "2024.02.03"

["J.md"]
title = "ğŸ¯ é…ç½®wgetä»£ç†"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/J.md"
comments = true

["K.md"]
title = "ğŸ é…ç½®curlä»£ç†"
emoji = ""
info = ""
cover = ""
path = "./0Software/1Linux/K.md"
date = "2023.10.13"
comments = true
