["A.md"]
title = "ğŸ¦¢ WSLå®‰è£…æŒ‡å®šç‰ˆæœ¬"
emoji = ""
info = ""
cover = ""
path = "./0Software/2WSL/A.md"
comments = true

["D.md"]
title = "ğŸ•Šï¸ WSLä¿®æ”¹åˆå§‹ç›®å½•"
emoji = ""
info = ""
cover = ""
path = "./0Software/2WSL/D.md"
comments = true

["E.md"]
title = "â˜ƒï¸ è°ƒç”¨WSLå‘½ä»¤"
emoji = ""
info = ""
cover = ""
path = "./0Software/2WSL/E.md"
comments = true
