[1sp]
title = "1sp"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/1sp"

["1ï¸âƒ£ ç”Ÿç‰©åŒ»å­¦ä¿¡å·å¤„ç†"]
title = "1ï¸âƒ£ ç”Ÿç‰©åŒ»å­¦ä¿¡å·å¤„ç†"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./ğŸ’ ä¿¡å·å¤„ç†/1ï¸âƒ£ ç”Ÿç‰©åŒ»å­¦ä¿¡å·å¤„ç†"

[2base]
title = "2base"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/2base"

["2ï¸âƒ£ åŸºç¡€çŸ¥è¯†"]
title = "2ï¸âƒ£ åŸºç¡€çŸ¥è¯†"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./ğŸ’ ä¿¡å·å¤„ç†/2ï¸âƒ£ åŸºç¡€çŸ¥è¯†"

[3filter]
title = "3filter"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/3filter"

["3ï¸âƒ£ æ»¤æ³¢å™¨è®¾è®¡"]
title = "3ï¸âƒ£ æ»¤æ³¢å™¨è®¾è®¡"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./ğŸ’ ä¿¡å·å¤„ç†/3ï¸âƒ£ æ»¤æ³¢å™¨è®¾è®¡"

[4experience]
title = "4experience"
emoji = ""
info = ""
cover = ""
path = "./6SignalP/4experience"

["4ï¸âƒ£ å¸¸ç”¨æŠ€å·§"]
title = "4ï¸âƒ£ å¸¸ç”¨æŠ€å·§"
emoji = ":simple-scipy:"
info = ""
cover = ""
path = "./ğŸ’ ä¿¡å·å¤„ç†/4ï¸âƒ£ å¸¸ç”¨æŠ€å·§"
