["A.md"]
title = "ğŸ¥ Ryeä½¿ç”¨æŒ‡å—"
emoji = ""
info = ""
cover = ""
path = "./1Python/1rye/A.md"
comments = true

["B.md"]
title = "ğŸ§© Ryeè¸©å‘è®°å½•"
emoji = ""
info = ""
cover = ""
path = "./1Python/1rye/B.md"
comments = true

["C.md"]
title = "ğŸ”« Ryeå®‰è£…Jupyter"
emoji = ""
info = ""
cover = ""
path = "./1Python/1rye/C.md"
comments = true

["D.md"]
title = "é…ç½®é¡¹ç›®Aè°ƒç”¨é¡¹ç›®B"
emoji = ""
info = ""
cover = ""
path = "./1Python/1rye/D.md"
date = "2025.04.11"
