["A.md"]
title = "ğŸƒï¸ å›¾ç‰‡å‹ç¼©"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2ï¸âƒ£ï¸ å›¾ç‰‡å‹ç¼©/A.md"
comments = true

["B.md"]
title = "ğŸƒï¸ å›¾ç‰‡å‹ç¼©(tinypng)"
emoji = ""
info = ""
cover = ""
path = "./7MyScripts/2ï¸âƒ£ï¸ å›¾ç‰‡å‹ç¼©/B.md"
comments = true
