["A.md"]
title = "ğŸ¦¢ WSLå®‰è£…æŒ‡å®šç‰ˆæœ¬"
emoji = ""
info = ""
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/2ï¸âƒ£ WSL/A.md"
comments = true

["D.md"]
title = "ğŸ•Šï¸ WSLä¿®æ”¹åˆå§‹ç›®å½•"
emoji = ""
info = ""
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/2ï¸âƒ£ WSL/D.md"
comments = true

["E.md"]
title = "â˜ƒï¸ è°ƒç”¨WSLå‘½ä»¤"
emoji = ""
info = ""
cover = ""
path = "./ğŸ€ è½¯ä»¶åŠé…ç½®/2ï¸âƒ£ WSL/E.md"
comments = true
