["0ï¸âƒ£ PyCharmé…ç½®"]
info = ""
emoji = ":simple-pycharm:"

["0ï¸âƒ£ åŸºç¡€ç¼–ç¨‹"]
info = ""
emoji = ":octicons-terminal-16:"

["0ï¸âƒ£ æ‰©å±•åº“"]
info = ""
emoji = ":simple-pypi:"

["1ï¸âƒ£ Ryeç›¸å…³"]
info = ""
emoji = ":simple-rye:"

["2ï¸âƒ£ Condaç›¸å…³"]
info = ""
emoji = ":simple-anaconda:"

["3ï¸âƒ£ pipç›¸å…³"]
info = ""
emoji = ":simple-python:"

["5ï¸âƒ£ Pythonå¯è§†åŒ–"]
info = ""
emoji = ":simple-python:"

["6ï¸âƒ£ Pythonç§‘å­¦è®¡ç®—"]
info = ""
emoji = ":simple-python:"

["7ï¸âƒ£ Pythonç½‘ç»œç¼–ç¨‹"]
info = ""
emoji = ":simple-python:"

["8ï¸âƒ£ Python GUIç¼–ç¨‹"]
info = ""
emoji = ":simple-python:"

["9ï¸âƒ£ Pythonç¡¬ä»¶ç¼–ç¨‹"]
info = ""
emoji = ":simple-python:"

["ğŸ”Ÿ å…¶ä»–"]
info = ""
emoji = ":simple-python:"
